### ISSUE TITLE
Make a geometric calculator

### ISSUE THREAD

**Issue by ion05** [akshitagit/Python#76]
Make a calculator for geometric figures like cube cuboid

**Comment by YuvrajSHAD** [comment]
I have Made a Calculator You May Check It. here is link 
https://github.com/akshitagit/Python

**Comment by ion05** [comment]
@akshitagupta15june can you assign me this issue ?

**Comment by YuvrajSHAD** [comment]
Ok


On Sep 26, 2020 at 17:27, aayan05 <notifications@github.com> wrote:

@akshitagupta15june <https://github.com/akshitagupta15june> can you assign
me this issue ?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akshitagit/Python/issues/76#issuecomment-699485738>, or
unsubscribe

**Comment by akshitagupta15june** [comment]
so has anyone raise pr regarding this issue?

**Comment by YuvrajSHAD** [comment]
Yes pr/77 has raised  this Issue


On Sep 26, 2020 at 22:39, AKSHITA GUPTA <notifications@github.com> wrote:

so has anyone raise pr regarding this issue?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akshitagit/Python/issues/76#issuecomment-699521985>, or
unsubscribe

**Comment by ion05** [comment]
> so has anyone raise pr regarding this issue?

I will in October otherwise it won't count. But my program is ready

**Comment by akshitagupta15june** [comment]
ok ok

**Comment by YuvrajSHAD** [comment]
Pr/77 created this Issue and I just work on that. I am really new so I
don't know to whom it's going and I am participating in hacktoberfest2020


On Sep 27, 2020 at 10:15, aayan05 <notifications@github.com> wrote:

so has anyone raise pr regarding this issue?

I will in October otherwise it won't count. But my program is ready

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akshitagit/Python/issues/76#issuecomment-699584790>, or
unsubscribe

**Comment by akshitagupta15june** [comment]
No problem if both of you are working on same issue.

**Comment by akshitagupta15june** [comment]
I have assigned to both of you

**Comment by YuvrajSHAD** [comment]
Ok


On Sep 27, 2020 at 10:25, AKSHITA GUPTA <notifications@github.com> wrote:

No problem if both of you are working on same issue.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/akshitagit/Python/issues/76#issuecomment-699585455>, or
unsubscribe

**Comment by adrputra** [comment]
Is there anyone already made PR for this issue?

**Comment by YuvrajSHAD** [comment]
Yes



On Oct 25, 2020 at 20:16, adrputra <notifications@github.com> wrote:

Is there anyone already made PR for this issue?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/akshitagit/Python/issues/76#issuecomment-716159840>, or
unsubscribe
